# SPDX-License-Identifier: MIT
---
- name: Configure all hosts
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all/vars.yml
  roles:
    - locales
    - ssh
    - ufw
    - fail2ban
    - detector
