name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "24"

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"

      - name: Install Python deps
        run: pip install -r requirements-dev.txt

      - name: Create dummy vault password file
        run: echo 'ci' > .vault_pass

      - name: Create dummy vault
        run: |
          printf -- '---\nvault_fail2ban_slack_webhook_url: ""\nvault_detector_report_webhook_url: ""\n' \
            > group_vars/all/vault.yml
          ansible-vault encrypt group_vars/all/vault.yml

      - name: Run pre-commit
        run: pre-commit run --all-files
